# Generated by Django 5.2.17 on 2026-10-03 19:14

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "Name must contain a non-whitespace character."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                django.db.models.functions.text.Trim("name")
                            ),
                            0,
                        ),
                        name="participant_name_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_received",
                        to="expenses.participant",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_paid",
                        to="expenses.participant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)), name="expense_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paid_by", models.F("expense_for")), _negated=True),
                        name="expense_different_participants",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.lookups.LessThanOrEqual(
                            django.db.models.functions.text.Length("description"), 500
                        ),
                        name="expense_description_bounded",
                    ),
                ],
            },
        ),
    ]
