# Generated by Django 5.2.17 on 2026-10-06 05:31

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "Name must contain a non-whitespace character."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                django.db.models.functions.text.Trim("name")
                            ),
                            0,
                        ),
                        name="occasion_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.lookups.LessThanOrEqual(
                            django.db.models.functions.text.Length("name"), 100
                        ),
                        name="occasion_name_bounded",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="occasion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.occasion",
            ),
        ),
    ]
