# Generated by Django 5.2.17 on 2026-10-06 07:00

import django.db.models.functions.text
from django.db import migrations, models


def reject_name_collisions(apps, schema_editor):
    occasions = apps.get_model("expenses", "Occasion").objects.using(schema_editor.connection.alias)
    duplicates = (
        occasions.annotate(normalized_name=models.functions.Lower(models.functions.Trim("name")))
        .values("normalized_name")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .order_by("normalized_name")
    )
    collisions = []
    for duplicate in duplicates:
        ids = list(
            occasions.annotate(
                normalized_name=models.functions.Lower(models.functions.Trim("name"))
            )
            .filter(normalized_name=duplicate["normalized_name"])
            .order_by("id")
            .values_list("id", flat=True)
        )
        collisions.append(str(ids))
    if collisions:
        raise RuntimeError(
            "Occasion names conflict after trimming and case-insensitive comparison. "
            "Conflicting occasion IDs: " + "; ".join(collisions) + ". "
            "Rename the distinct occasions explicitly, preserving IDs and expense assignments, "
            "then retry migration 0003. No rows have been changed or merged."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_occasions"),
    ]

    operations = [
        migrations.RunPython(reject_name_collisions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="occasion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("name")),
                name="occasion_name_ci_unique",
            ),
        ),
    ]
